apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
        - image: docker.io/chrisgreene/knative-tekton
          imagePullPolicy: Always
          env:
            - name: TARGET
              value: boom
